#!/usr/bin/env bash
# A Bash script that continuously displays the message 
# "To infinity and beyond," is resilient to termination signals (SIGTERM),
# and responds with "I am invincible!!!" when a SIGTERM is received.

# The 'trap' command sets a custom action to be executed
# when a SIGTERM signal is received.
trap 'echo "I am invincible!!!"' SIGTERM

# Enter an infinite loop that repeatedly echoes the message
#"To infinity and beyond."
while true; do
    echo "To infinity and beyond"
    sleep 2
done
