#!/usr/bin/env bash
# Indefinitely writes "I am alive" to the file /tmp/my_process.
# Pauses two seconds in between each message.

while true
do
  # Append "I am alive!" to the file /tmp/my_process.
  echo "I am alive!" >> /tmp/my_process
  # Pause for two seconds before the next iteration.
  sleep 2
done
