#!/usr/bin/env bash
# This Bash script is designed to display the text "Best School" 10 times.

# Using a for loop to iterate 10 times
for ((i = 0 ; i < 10 ; i++)); do
  # Printing "Best School" to the standard output
  echo "Best School"
done
