#!/usr/bin/env bash
# This Bash script is designed to implement the FizzBuzz
# program from 1 to 100.

# Initializing a variable 'i' with the value 1
i="1"

# Using a 'while' loop to iterate through numbers from 1 to 100
while [ $i -lt 101 ]
do
  # Checking if 'i' is a multiple of 15 (divisible by both 3 and 5)
  if (( i % 15 == 0 )); then
    # If 'i' is a multiple of 15, it prints "FizzBuzz" to
    # the standard output
    echo "FizzBuzz"
  # Checking if 'i' is a multiple of 5
  elif (( i % 5 == 0 )); then
    # If 'i' is a multiple of 5, it prints "Buzz" to the standard output
    echo "Buzz"
  # Checking if 'i' is a multiple of 3
  elif (( i % 3 == 0 )); then
    # If 'i' is a multiple of 3, it prints "Fizz" to the standard output
    echo "Fizz"
  else
    # If 'i' is not a multiple of 3, 5, or 15, it prints the value of 'i'
    echo $i
  fi
  
  # Incrementing the 'i' variable by 1 for the next iteration
  i=$((i+1))
done
