#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

# Using a 'while' loop to read fields from the file
# '/etc/passwd', separated by colons (:)
while IFS=':' read -r username password uid gid info home shell; do
  # Printing a story about each user based on the extracted fields
  echo "The user $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done < "/etc/passwd"
