#!/usr/bin/env bash
# Parses Apache log files in list format, groups
# visitors by IP and HTTP status code,
# and displays the number of occurrences, IP, and
# HTTP status code of each log, in sorted order.

# Using 'awk' to extract the IP address and HTTP
# status code from the Apache log file 'apache-access.log'
# and combining them into a single line separated by a space.
awk '{ print $1 " " $9}' apache-access.log |

# Sorting the combined lines, grouping logs by IP and HTTP status code.
sort |

# Counting the number of occurrences of each unique
# line (i.e., IP and HTTP status code combination)
# and prefixing the count to each line.
uniq -c |

# Sorting the results in reverse numerical order
# (descending order) based on the count.
sort -rn
