#!/usr/bin/env bash
# This Bash script is designed to display
# the text "Best School" 10 times.

# Initializing a variable 'i' with the value 0
i="0"

# Using a 'while' loop to iterate as long
# as 'i' is less than 10
while [ $i -lt 10 ]
do
  # Printing "Best School" to the standard output
  echo "Best School"
  
  # Incrementing the 'i' variable by 1
  i=$((i+1))
done
