#!/usr/bin/env bash
# This Bash script is designed to display 
# "Best School" 10 times and "Hi" once.

# Initializing a variable 'i' with the value 0
i="0"

# Using a 'while' loop to iterate while 'i' is less than 11
while [ $i -lt 11 ]
do
  # Checking if 'i' is equal to 9
  if (( i == 9 )); then
    # If 'i' is equal to 9, it prints "Hi" to the standard output
    echo "Hi"
  else
    # If 'i' is not equal to 9, it prints "Best School" to the standard output
    echo "Best School"
  fi
  
  # Incrementing the 'i' variable by 1
  i=$((i+1))
done
