#!/usr/bin/env bash
# This Bash script is designed to display numbers from 1
# to 20 and provide special messages for certain numbers.

# Initializing a variable 'i' with the value 1
i="1"

# Using a 'while' loop to iterate while 'i' is less than 21
while [ $i -lt 21 ]
do
  # Printing the value of 'i' to the standard output
  echo $i
  
  # Using a 'case' statement to check the value of 'i'
  # and provide special messages for certain numbers
  case $i in
    "4" )
      # If 'i' is equal to 4, it prints "bad luck from
      #  China" to the standard output
      echo "bad luck from China"
      ;;
    "9" )
      # If 'i' is equal to 9, it prints "bad
      #  luck from Japan" to the standard output
      echo "bad luck from Japan"
      ;;
    "17" )
      # If 'i' is equal to 17, it prints "bad
      #  luck from Italy" to the standard output
      echo "bad luck from Italy"
      ;;
  esac
  
  # Incrementing the 'i' variable by 1
  i=$((i+1))
done
