#!/usr/bin/env bash
# This Bash script is designed to display the hours
#  and minutes in a 12-hour clock format.

# Initializing variables 'hour' and 'min' with initial values
hour="0"
min="1"

# Using an outer 'while' loop to iterate through the
#  hours from 0 to 12
while [ $hour -lt 13 ]
do
  # Printing the current hour
  echo "Hour: $hour"
  
  # Using an inner 'while' loop to iterate through the
  #  minutes from 1 to 59
  while [ $min -lt 60 ]
  do
    # Printing the current minute
    echo $min
    
    # Incrementing the 'min' variable by 1
    min=$((min+1))
  done
  
  # Resetting the 'min' variable to 1 for the next hour
  min="1"
  
  # Incrementing the 'hour' variable by 1 for the next hour
  hour=$((hour+1))
done
