#!/usr/bin/env bash
# This Bash script is designed to print an empty line once.

# Using a 'for' loop that iterates once (i.e., with
# 'i' starting at 0 and ending at 1)

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
