#!/usr/bin/env bash
# Displays information about the `school` file.

# Checking if the file "school" exists
if [ -e "school" ]
then
  # If it exists, print that the file exists
  echo "school file exists"

  # Checking if the file "school" is not empty
  if [ -s "school" ]
  then
    # If it's not empty, print that the file is not empty
    echo "school file is not empty"
  else
    # If it's empty, print that the file is empty
    echo "school file is empty"
  fi

  # Checking if the file "school" is a regular file
  if [ -f "school" ]
  then
    # If it's a regular file, print that it's a regular file
    echo "school is a regular file"
  fi
else
  # If the file does not exist, print that it does not exist
  echo "school file does not exist"
fi
