#!/usr/bin/env bash

# Define variables
key_name="school"
key_bits="4096"
passphrase="betty"

# Create RSA key pair with passphrase
ssh-keygen -t rsa -b 4096 -f school -N betty

echo "RSA key pair created successfully."
echo "Private key: $key_name"
echo "Public key: ${key_name}.pub"
